### ISSUE TITLE
Multiple GUIs on Launch

### ISSUE THREAD

**Issue by sahasatvik** [SupritBehera/Scale-Generator_WithGUI#1]
Pressing 'Launch' initiates a new GUI.

Suggested fix below.

```java
//ScaleGenerator.java
...
public class ScaleGenerator {
	GUI gui;
	ScaleGenerator(GUI gui) {
		this.gui = gui;
...
```
```java
//GUI.java
...
    public void runScaleGenerator() {
		new ScaleGenerator(this);
	}
...
```

**Comment by SupritBehera** [comment]
Your suggested fix has been implemented. Thanks for the help !

**Comment by sahasatvik** [comment]
The code still doesn't compile! You forgot to change the call to `ScaleGenerator` in `GUI.java`

``` java
//GUI.java
...
    public void runScaleGenerator() {
        new ScaleGenerator(this);
    }
...
```

**Comment by SupritBehera** [comment]
The issue has been fixed. The original file (without the changes) inadvertently had been re-uploaded again.
